### ISSUE TITLE
Problems with multiple corrections when using ERSP

### ISSUE THREAD

**Issue by mglassen** [LIMO-EEG-Toolbox/limo_tools#104]
Hi all,

I am using the integrated version of LIMO with EEGLABs study, and Im having some issues. I testing a simple comparison(1 factor, 2 categorical values) for 19 subjects. 1st level analysis runs successfully, and for 2nd level analysis I did a paired-t test which also ran fine. When using LIMO results I can plot uncorrected stat values and the plots appear and everything works, but I run into issues when trying to use multiple corrections. When I use TFCE, I get an error in limo_tfce at line 723. When appending neg_tfce and pos_tfce to the thresholded_maps variable, thresholded maps is 3d and neg_tfce is 4d,(as is pos_tfce). I would try and fix this myself but the theory behind the clustering is a little beyond me. 

I also get an error when trying to use the Cluster MCC as well, but I can't pinpoint whats happening in the code because MATLABs debugger doesn't pause on this error, I just get a dialog box that pops up and says there is no function limo_cluster_test for input arguments of type double.

Any help with this issue would be appreciated! I pasted the loop where the error occurs from the TFCE part below.

  % compute final score
                    tfce_score = nansum(pos_tfce,4)+nansum(neg_tfce,4);
                    try close(f); end
                    if nargout == 2
                        
                        thresholded_maps = NaN(size(pos_tfce,1),size(pos_tfce,2),...
                          size(neg_tfce,3)+size(pos_tfce,3));
                      
                        thresholded_maps(:,:,size(neg_tfce,3):-1:1)  = neg_tfce;
                        thresholded_maps(:,:,size(neg_tfce,3)+1:end) = pos_tfce;
                        thresholded_maps(:,:,squeeze(sum(squeeze(sum(thresholded_maps,1)),1))==0) = [];
                    end

**Comment by CPernet** [comment]
ok that is weird, all tests give 4d matices ... would you mind sharing your group level folder so I can rerun the clustering and see what is happening? thx

**Comment by CPernet** [comment]
quickly checking is this is resolved or not?

**Comment by mglassen** [comment]
Sorry I missed your original reply, I’ll put the data up on Monday.

Best,
Mike

**Comment by CPernet** [comment]
great, happy to fix that for you

**Comment by CPernet** [comment]
??? I'll close this since I had no news
