### ISSUE TITLE
limo_preproc_stats_hw error

### ISSUE THREAD

**Issue by arnodelorme** [LIMO-EEG-Toolbox/limo_tools#107]
Version in https://github.com/sccn/eeglab_tests/tree/master/unittesting_limo

Crash on the call to pop_limo
```
STUDY  = pop_limo(STUDY, ALLEEG, 'method',mode,'measure','daterp','timelim',[-50 650],'erase','on','splitreg','off','interaction','off');
```

The error message is below

```
Error using limo_WLS (line 43)
WLS cannot be computed, for at least 1 condition, all trials have the same values

Error in limo_glm (line 172)
    [Betas,W,rf] = limo_WLS(X,Y);

Error in limo_glm_handling (line 111)
            model = limo_glm(squeeze(Yr(channel,:,:))',LIMO);

Error in limo_eeg (line 476)
            limo_glm_handling(LIMO)

Error in psom_pipeline_debug (line 11)
    eval( [ commands.(fields1{iField1}).command ] );

Error in limo_batch (line 488)
        psom_pipeline_debug(pipeline(subject));

Error in std_limo (line 553)
    [LIMO_files, procstatus] = limo_batch('model specification',model,[],STUDY);

Error in pop_limo (line 168)
[STUDY,limofiles] = std_limo(STUDY, ALLEEG, options{:});

Error in limo_preproc_stats_hw (line 79)
STUDY  = pop_limo(STUDY, ALLEEG, 'method',mode,'measure','daterp','timelim',[-50 650],'erase','on','splitreg','off','interaction','off');
 
43      error('WLS cannot be computed, for at least 1 condition, all trials have the same values')
```

**Comment by CPernet** [comment]
doesn't look like an error to me - that part of the code has been there for a long time, so maybe the data you use for testing are different?

if isempty(Y(:,mad(Y,1) > 1e-6)) % time points for which medians of trials > 1e-6
    error('WLS cannot be computed, for at least 1 condition, all trials have the same values')
end

 Y  = 2D matrix of EEG data (dim trials x frames) tells you that all frames have values not deviating more than 1e-6, i.e. data = a constant value  (but I use 1e-6 because of precision errors)

**Comment by arnodelorme** [comment]
I am testing the Hanson Wakeman data with the script provided. Can you try it?

**Comment by CPernet** [comment]
I have not reprocessed the data, but for me https://github.com/LIMO-EEG-Toolbox/limo_test_stats/blob/master/limo_test_integration.m worked

I have now [added design with a constant only](https://github.com/LIMO-EEG-Toolbox/limo_test_stats/commit/6e747a5c36aa3bf22cfb5d319f3e688cb3187e8c) and it worked as well (with the [added fix in std_limo](https://github.com/sccn/eeglab/commit/7a3f7ef851099f7bc542805cc0a6b92bb84e28f6)) -- I really think the issue are the data in ...

**Comment by CPernet** [comment]
WLS doesn't fail, this issue moved on another topic due to bad data in
