### ISSUE TITLE
Default Beta file

### ISSUE THREAD

**Issue by arnodelorme** [LIMO-EEG-Toolbox/limo_tools#111]
For 2nd level, LIMO should be proposing BETA files (with an option to load manually).
Naive users have no idea what to do.

**Comment by CPernet** [comment]
?? the expert user I am have no idea what you are talking about

**Comment by arnodelorme** [comment]
See how complex it is.

When you are at the second level, if you want to do any stats, you need to select a Beta file. However, users have no idea. I want to implement a "noob" mode, where you can actually get something done without spending hours on documentation.

**Comment by CPernet** [comment]
ah we discussed this from the day I showed you hierarchical models, 10+ year ago. The way variables are organized at 1st level doesn't translate necessary to group level, You cannot know what people what to do from 1st level design and thus cannot propose options. We tried, Ramon was running many one sample t-test automatically, etc ... yeh type one error to the roof and no meaning.
