### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by arnodelorme** [LIMO-EEG-Toolbox/limo_tools#112]
In file limo_contrast_manager line 432 we have

```matlab
            limo_contrast(Yr,LIMO,3);
```

Yet, limo_contrast crashes if there are less than 4 parameters because the variable type is undefined. This is using the HotFixes branch

```matlab
if nargin == 5 || nargin == 6
    type = varargin{5};
elseif nargin == 4
    type = varargin{3};
end
```

**Comment by CPernet** [comment]
nope, la je viens juste de faire la GUI, ca run no problem

**Comment by arnodelorme** [comment]
Ca crashe pour moi. Face dataset, ensuite je fais une ANOVA comme dans le tuto. Ensuite je crais un contraste. 

Si tu regardes le code, tu veras que si tu passes par la ligne 432, cela ne peux pas marcher.

**Comment by CPernet** [comment]
on it

**Comment by CPernet** [comment]
done

**Comment by arnodelorme** [comment]
Super

**Comment by arnodelorme** [comment]
![Screen Shot 2022-09-09 at 12 24 53 AM](https://user-images.githubusercontent.com/1872705/189295186-b243ac7d-2bd9-41bc-8137-32e00cdb24d3.png)

**Comment by arnodelorme** [comment]
Mon nouveau menu pour selectionner les betas.

**Comment by CPernet** [comment]
wow selection des betas rapellant ce que c'est + GUI -- je m'incline maitre Arno :-) trop fort

**Comment by arnodelorme** [comment]
Tu peux entrer les indices comme avant en bas si tu veux et si l'etude n'existe pas, il utilise l'ancien menu

**Comment by arnodelorme** [comment]
Et cela marche.

**Comment by arnodelorme** [comment]
OK, c'est bon pour ce bug
