### ISSUE TITLE
Replace NaNs by 0 for continuous variables at the 1st level (reaction time)

### ISSUE THREAD

**Issue by arnodelorme** [LIMO-EEG-Toolbox/limo_tools#118]
I put it here, so we do not forget. Should we have a checkbox in pop_limo asking users if they want to replace NaNs by 0 if a lot of NaNs are detected for a continuous variable?

**Comment by CPernet** [comment]
Actually, it was doing it line 163 -- but it would necessarily fail testing singularity det(Cont'*Cont) == 0.
I just moved the the code ; does it do what you wanted? https://github.com/LIMO-EEG-Toolbox/limo_tools/commit/4048aedf1d7acbd82750110405b24f8ae71ff86e
