### ISSUE TITLE
[Question] limo_create_boot_table: subject number check

### ISSUE THREAD

**Issue by amisepa** [LIMO-EEG-Toolbox/limo_tools#121]
Hi,

line 49, when checking number of subjects: 
```
if size(data,3)-1 <= Nmin
    error(['Not enough subjects in dataset - need at least ' num2str(Nmin) ' subjects']);
end
```

--> I was doing a simple test with 4 subjects and got the error that there were only 3 subjects because of the -1.
Is this an error or does it have a purpose? When I remove it, the function worked fine.

Thanks,

Cedric

**Comment by CPernet** [comment]
because the stats under Nmin make no sense , not a bug Cedric

**Comment by amisepa** [comment]
I know it wouldn't if I had 3 subjects, but I am pointing out that even with 4 subjects (i.e. one more than Nmin), I get the error. Why is there -1 is my question

**Comment by amisepa** [comment]
Ah ok thanks!
