### ISSUE TITLE
Contrast level 1

### ISSUE THREAD

**Issue by arnodelorme** [LIMO-EEG-Toolbox/limo_tools#122]
While at level 2, contrast are stored in LIMO.mat, this is not the case for level 1. As far as I understand, once a contrast has been computed on level 1, there is no way to reconstruct what it was about.

**Comment by CPernet** [comment]
LIMO.contrast a cell array
Indicated t or F
Indicate the contrast itself

**Comment by arnodelorme** [comment]
Level one does not contain LIMO.contrast

**Comment by CPernet** [comment]
It does - but likely inconsistently saved.
How did you compute it?
Try GUI 1 subject is works, i believe it works for LIMO batch too?

**Comment by arnodelorme** [comment]
I think this was computed automatically by std_limo.m
I can try to see if I can reproduce the problem (lack of contrast field while the con files is computed.

**Comment by CPernet** [comment]
OK I'll track that bug 🐛 down

**Comment by CPernet** [comment]
well from STUDY it works, combine variables = create contrasts ; and LIMO.contrast has them all -- the GUI finds them too! but it bugged for display 

![image](https://user-images.githubusercontent.com/4772878/192584726-6f654760-8b3f-4994-99ed-14066a536611.png)
