### ISSUE TITLE
TFCE error

### ISSUE THREAD

**Issue by arnodelorme** [LIMO-EEG-Toolbox/limo_tools#127]
Not sure where it comes from (GUI popup). Could not trace it back.

**Comment by arnodelorme** [comment]
![Screen Shot 2022-09-27 at 7 59 14 PM](https://user-images.githubusercontent.com/1872705/192690740-0493b535-f0ac-4291-8b1a-a34b63bb02ab.png)

**Comment by CPernet** [comment]
solved? I haven't had that error in any tests (or analyses for that matter)
