### ISSUE TITLE
ANOVA

### ISSUE THREAD

**Issue by arnodelorme** [LIMO-EEG-Toolbox/limo_tools#128]
So it is not possible to do groups of subjects and sessions (because we cannot do nested) right?
However it is possible to do groups or sessions. How do you define paired groups or unpaired groups? (sessions are always paired obviously)

**Comment by CPernet** [comment]
' How do you define paired groups or unpaired groups?'
groups are never paired, they are groups -- what we have is
- [robust 1-way ANOVA](https://github.com/LIMO-EEG-Toolbox/limo_tools/blob/master/limo_robust_1way_anova.m), non-nesting of as many groups as you want
- [repeaed measure ANOVA](https://github.com/LIMO-EEG-Toolbox/limo_tools/blob/master/limo_rep_anova.m) stuill trying to robustify it ... non-nesting of as many groups as you want + repeated measures

no one requested it, but we can do nested N-ways ANOVA just by calling limo_glm.m
