### ISSUE TITLE
limo_ft_findcluster duplicate?

### ISSUE THREAD

**Issue by arnodelorme** [LIMO-EEG-Toolbox/limo_tools#130]
limo_getclustersum.m uses limo_ft_findcluster while all other LIMO functions use limo_findcluster

Aren't the two functions equivalent? Why was limo_findcluster programmed by the way?

**Comment by CPernet** [comment]
well spotted !! line 25 change to limo_findcluster  = 2/3 faster
as indicated in the limo_findcluster function this is for speed see https://github.com/LIMO-EEG-Toolbox/limo_cluster_test 
note that this should call spm_bwlabel located in eeglab\plugins\limo_tools\external\spm_bwlabel

**Comment by arnodelorme** [comment]
Not so fast. I have made a change that boost performance as well (remove the find) as recommended by MATLAB.

**Comment by CPernet** [comment]
read the doc -- limo_findcluster function = 60% faster

**Comment by arnodelorme** [comment]
I have removed the find in limo_cluster not the Fieldtrip function. Also I am trying to compile it in C. We can compare the speed.

**Comment by CPernet** [comment]
just use that function gonna -- this was written for that, and as you said all over limo stuff call this
