### ISSUE TITLE
[BUG] version check for parallel toolbox breaks compatibility with Matlab 2018a (worked previously)

### ISSUE THREAD

**Issue by jnvandermeer** [LIMO-EEG-Toolbox/limo_tools#147]
**Describe the bug**

Estimating the LIMO parameters yields an error : "All of the input arguments must be of the same size and shape.
Previous inputs had size 11 in dimension 2. Input #3 has size 1".

**To Reproduce**
Estimate LIMO parameters with Matlab 2018a.

In limo_check_ppool.m, there is line 11, on which is written:
"strcmpi('Parallel Computing Toolbox',arrayfun(@(x) x.Name, addons, "UniformOutput",false))"

This does not work in Matlab 2018a. A solution is to just replace this with 0, which skips detection of the parallel toolboxes. or to replace with:
strcmpi('Parallel Computing Toolbox',{addons.Name})
Which is probably not super clean. But, the arrayfun(@) implementation does not work well for structs in older versions of matlab.

**Comment by CPernet** [comment]
what about:
```matlab
addons = ver;  
if any(ismember('Parallel Computing Toolbox', {addons.Name}))  
   ...  
end
```

does that work for your Matlab version?  (yes noticed older versions do not take cell array in in many functions like strcmp, contains, etc)

**Comment by jnvandermeer** [comment]
Yes, that works fine on my older Matlab 2018a.

Many thanks!
Johan

**Comment by CPernet** [comment]
great, thx - solved by https://github.com/LIMO-EEG-Toolbox/limo_tools/commit/f2ac7272103e1ff809de706b8fda0c2646690924
