### ISSUE TITLE
limo_stat_values when running for only one channel Repeated Measures ANOVA, with temporal cluster correction, has a mistake [BUG]

### ISSUE THREAD

**Issue by mariajribeiro** [LIMO-EEG-Toolbox/limo_tools#149]
in limo_stat_values if running for just one channel, Repeated Measures ANOVA, with temporal cluster correction, line 371 should be:

tmp = NaN(1,size(M,2),size(bootT,2));

instead of 
tmp = NaN(1,size(M,2),size(bootT,4));

bootT has only 2 dimensions

**Comment by CPernet** [comment]
hey thx Maria! good to see you are still playing with the tool :-)
fixed https://github.com/LIMO-EEG-Toolbox/limo_tools/commit/1652db61924033e62975861b645fd4bac70d2525

**Comment by mariajribeiro** [comment]
you're welcome! still finding limo_eeg very useful. hopefully finishing a manuscript soon.
