### ISSUE TITLE
[BUG] regression Yr.mat inverted subjects

### ISSUE THREAD

**Issue by sarbula** [LIMO-EEG-Toolbox/limo_tools#153]
After doing the regression analysis, the Yr.mat contains the data, but the order of the subjects is inverted (the first subject becomes the last). This seems to affect the results since the covariate is not inverted.

**Comment by sarbula** [comment]
Just to check, this bug was present since the early versions of LIMO? We have some results from the analyses we ran few years ago, but now with this fix they completely changed..
Thanks

**Comment by CPernet** [comment]
mmh looking at the history looks like the bug is there since 2020

**Comment by sarbula** [comment]
we got significant results both then and now, but in different time windows and electrodes... we figured out something was wrong when we started plotting directly betas... 
thanks
