### ISSUE TITLE
cluster correction plot failure [BUG]

### ISSUE THREAD

**Issue by amisepa** [LIMO-EEG-Toolbox/limo_tools#156]
on HotFixes branch, getting this error when trying to plot results with spatiotemporal cluster correction:

![image](https://github.com/LIMO-EEG-Toolbox/limo_tools/assets/58382227/3ced2d34-eb58-498d-a50a-22e5d9d89321)

Max and TFCE are working fine.

**Comment by amisepa** [comment]
I added the path to the \limo_cluster_functions folder and it fixed the issue. Shouldn't eeglab add the path to subfolders automatically?

**Comment by cmmrandau** [comment]
Same issue here, always have to add this folder each time I re-install
LIMO.

**Comment by CPernet** [comment]
it is added automatically but only if using [limo_eeg](https://github.com/LIMO-EEG-Toolbox/limo_tools/blob/master/limo_eeg.m#L32) or [std_limo](https://github.com/sccn/eeglab/blob/develop/functions/studyfunc/std_limo.m#L137) .. I have now added it also in limo_stat_values which should fix calls to clustering functions, see this [commit](https://github.com/LIMO-EEG-Toolbox/limo_tools/commit/5327bfb23e1ff04851bbc2c8b9cf087a444d4091#diff-b1a9705d4ca8ca39a430f5fdfb81b1b2ebed558999ecb3894ad3723aaba53834)
  
also updated [instalation JIC](https://github.com/LIMO-EEG-Toolbox/limo_tools/commit/0dbe672b5d359a8eb37b0058db53b9333fbb1582)

**Comment by amisepa** [comment]
thanks!
