### ISSUE TITLE
[BUG] limo_rep_anova.m 

### ISSUE THREAD

**Issue by mariajribeiro** [LIMO-EEG-Toolbox/limo_tools#157]
Error in limo_rep_anova.m line 398

running from script repeated measures ANOVA
limo_random_robust(6,y,gp,factor_levels,LIMO,'go', 'no')
with 2 within-subject factors

in limo_rep_anova.m enters

case{4} % several within and 1 between factors

lines 398 and 399

result.interaction.df(effect,c)  = unique(df); 
result.interaction.dfe(effect,c) = unique(dfe);

variable c is the contrasts with 1 and -1 and cannot be assigned as an index

it runs by deleting (effect, c) in lines 398 and 399

result.interaction.df = unique(df); 
result.interaction.dfe = unique(dfe);

but not sure if that is correct?

I also have a doubt regarding running this analysis from script.
I am running it skipping Level 1 (because I have no way of extracting single trials for these conditions), so I am using as input (measures) the ERPs from each factor - I have 2 within-subject factors (A and B) with 2 levels each (A1 A2 and B1 B2), so the input will be A1B1 A1B2 A2B1 A2B2, right? Which factor does LIMO consider factor 1 and factor 2?
           
Thanks!
Maria Ribeiro

**Comment by CPernet** [comment]
is that due to this? https://github.com/LIMO-EEG-Toolbox/limo_tools/commit/1990a55d2ac3e2981b2ae94eda9ffd623d88b3bf

**Comment by CPernet** [comment]
solved?
