### ISSUE TITLE
[Question] frame/trial ratio warning when running limo_pcout

### ISSUE THREAD

**Issue by amisepa** [LIMO-EEG-Toolbox/limo_tools#178]
I have 229 trials (ERP data) with sampling rate 1000 Hz, and get this warning: 

`8.73362 frame/trial ratio is very low, running SVD as usual but consider using OLS rather than WLS especially if you have a low sampling rates `

Is this to be expected? >200 trials with this kind of sampling rate is pretty standard, isn't it? Do I need to run OLS optimization?

**Comment by CPernet** [comment]
it's up to you - see https://apertureneuropub.cloud68.co/articles/51/#discussion - which is why it is there as a warning
if your power analysis works with 500Hz it might be better (not sure)

**Comment by amisepa** [comment]
I see, thank you for the link. 
when there arent' enough frames per trial, and downsampling is not enough, is it possible to accounting for data rank when running PCA to avoid data rank deficiencies. Similar to what's done for ICA in EEGLAB; see for example [Kim et al. (2022)](https://www.frontiersin.org/articles/10.3389/frsip.2023.1064138/full)?

**Comment by CPernet** [comment]
as per discussion in the paper, we only look at the trade off -- here I'm not trying to decompose the data per se, but reproject into a less dense space, no idea how that would affect outlier detection
