### ISSUE TITLE
[BUG] Bug with limo_random_select

### ISSUE THREAD

**Issue by npdrbong** [LIMO-EEG-Toolbox/limo_tools#181]
I am doing RM-ANOVA on 3 conditions with 3 con files.

limo_random_select('Repeated Measures ANOVA',chanlocs,'LIMOfiles', {con1_files,con2_files,con3_files},...
    'analysis_type','Full scalp analysis','parameters',{[1 1 1]},...
    'factor names',{'Condition'},'type','Channels','nboot',1000,'tfce',0,'skip design check','yes');

It worked with 2021-12-21 version of LIMO, but I want to do it again with current version(to use improved gui version).
However, error message with below poped up.

Unrecognized function or variable 'gp_val'.

Error in limo_random_select (line 1145)
    gp_nb = cell2mat(limo_inputdlg('How many independent groups of subjects or session per subject?','Groups', 1, {gp_val}));

I am using master branch of limo 4.0 and GUI version work properly.

I don't know what's wrong with this. Thanks!

**Comment by CPernet** [comment]
the issue is {con1_files,con2_files,con3_files}, what does that look like? if you do data = {con1_files,con2_files,con3_files} does it show a single group (row) and repeated measures in columns ; should be easy to fix, just need to make sure/understand where the error stems from

**Comment by CPernet** [comment]
fixed - at least for me - https://github.com/LIMO-EEG-Toolbox/limo_tools/commit/faf029d0c22f618cccdbee10005569c9f68a84cb#diff-3e180498c3a57bb83c4fac7312f882d46ee7ce13b631be64332856907e3d6583, pull from master and try again with your code

**Comment by npdrbong** [comment]
Thank you, Cyril! Have a nice day! Problem solved.
