### ISSUE TITLE
[BUG] limo_display_results error when regression among subjects

### ISSUE THREAD

**Issue by npdrbong** [LIMO-EEG-Toolbox/limo_tools#183]
I am doing statistics with reference on tutorial:
https://github.com/LIMO-EEG-Toolbox/limo_meeg/wiki/11.-Regression-among-subjects

and I got error message with current version.

It works well with version 20211221

>> limo_display_results(3,'Covariate_effect_1.mat',pwd,0.05,1,...
    fullfile(pwd,'LIMO.mat'),0,'channels',28,'plot3type','Modelled'); % course plot
Index exceeds the number of array elements. Index must not exceed 3.

Error in limo_display_results (line 88)
    extra = extra{g.plot3type};
 

>> changed limo 4.0 master(current version) -> limo 20211221

>> limo_display_results(3,'Covariate_effect_1.mat',pwd,0.05,1,...
    fullfile(pwd,'LIMO.mat'),0,'channels',28,'plot3type','Modelled'); % course plot
saveas(gcf, 'contrast_timecourse.fig'); close(gcf)
 
limo_display_results 15h 4min 48.237sec: making figure...

**Comment by CPernet** [comment]
fixed :-) https://github.com/LIMO-EEG-Toolbox/limo_tools/commit/ea7b0c037cb83d50acb237c565cd82b66bc82de7
