### ISSUE TITLE
[BUG] cannot save limo_eeg(pwd, 5) with ERSP result

### ISSUE THREAD

**Issue by npdrbong** [LIMO-EEG-Toolbox/limo_tools#184]
When I try to do ERSP with current version of LIMO, it doesn't save figure automatically.
figure pop up with limo_eeg(pwd, 5) and mask and p_values are ok, but it doesn't save figure.
![image](https://github.com/LIMO-EEG-Toolbox/limo_tools/assets/102932662/72124ea3-2a96-4cef-9f53-b5fb14bab670)

If I try to save figure with gui(file -> save as) : 
>> limo_eeg(5,pwd)
using cached data
Error using checkArgsForHandleToPrint
Specify one graphics object, a vector of graphics objects, or a cell array of graphics objects.

Error in checkArgsForHandleToPrint

Error in print>LocalCreatePrintJob (line 108)
handles = checkArgsForHandleToPrint(0, varargin{:});

Error in print (line 38)
[pj, inputargs] = LocalCreatePrintJob(varargin{:});

Error in limo_display_image_tf>PrintMenuItem_Callback (line 540)
print(fig_id,'-depsc2',[name '.eps'])

Error in gui_mainfcn (line 95)
        feval(varargin{:});

Error in limo_display_image_tf (line 29)
    gui_mainfcn(gui_State, varargin{:});

Error in matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)limo_display_image_tf('PrintMenuItem_Callback',hObject,eventdata,guidata(hObject))
 
Error while evaluating Menu Callback.

---------------------------------------------------------------

Thank you a lot!

**Comment by CPernet** [comment]
yeh v4 has no GUI for ERSPbecause it looks for input that we have changed - @arnodelorme is in charge of that part since is the master of interactive plotting in EEGLAB and let's face it I'm not very good at that

**Comment by qushiyan** [comment]
Hello, have you successfully run the GUI for ERSP? I keep getting an error about incorrect data dimensions when I perform the first-order analysis, but I don't have any issues when running spec or erp.
