### ISSUE TITLE
to run t-test without trimmed means - alpha level missing in limo_random_robust[BUG]

### ISSUE THREAD

**Issue by mariajribeiro** [LIMO-EEG-Toolbox/limo_tools#185]
limo_random_robust line 400

[~,~,~,~,~,t{b},p{b}]=limo_ttest(2,Y1(1,:,boot_table1{channel}(:,b)),Y2(1,:,boot_table2{channel}(:,b)));

it crashes in limo_ttest because variable alphav is missing.
fixed by adding extra input variable with alpha level.

**Comment by CPernet** [comment]
Hi Maria, 
ok will do - can you tell me why you use LIMO.design.method ='Mean' rather then the default?

**Comment by mariajribeiro** [comment]
Hi. I am trying this because there was an obvious difference in means and I was checking if the lack of significant clusters was because of the trimmed means. Obviously, these differences not very "robust" :(

**Comment by CPernet** [comment]
fixed in 3.4 and master, thx
