### ISSUE TITLE
limo_display_image overwritten by a different function

### ISSUE THREAD

**Issue by arnodelorme** [LIMO-EEG-Toolbox/limo_tools#187]
In this commit 2 weeks ago

https://github.com/LIMO-EEG-Toolbox/limo_tools/commit/de5354d1ca3d1b3ef676b8e463d704bb8dc58b02

This is a real serious bug that breaks everything. Do not ignore it :-).

**Comment by CPernet** [comment]
you can reverse it if you want - except changing p value, everything else works from me.

**Comment by arnodelorme** [comment]
You overwrote a working function with something else. I can fix it, but it might take months until I use LIMO again and get to that.

**Comment by CPernet** [comment]
Only the display because you wanted the empty map to show

**Comment by CPernet** [comment]
solved
