### ISSUE TITLE
[Question]EEGLAB error in function limo_batch() at line 569: undefined function 'gcp' for input arguments of type 'char'

### ISSUE THREAD

**Issue by helentobback** [LIMO-EEG-Toolbox/limo_tools#188]
Dear,

I set up a study containing several datasets and want to run LIMO on it. When estimating the model parameters I get the above error. Is there any way you could help me with fixing this problem? I already coppied the most recent version of the limo_batch function code and updated and installed all most recent versions of Matlab and Eeglab.

**Comment by CPernet** [comment]
solved by https://github.com/LIMO-EEG-Toolbox/limo_tools/commit/0c6e82eac42836cd8667b0669ad7ce8e39cc622f#diff-0a48b7e26b79c71936bfc2b68752925c367ff3e1ae665e75fc241f2269fd59ae
