### ISSUE TITLE
Unable to perform cluster analysis using LIMO toolbox in matlab

### ISSUE THREAD

**Issue by sgovindaswamy** [LIMO-EEG-Toolbox/limo_tools#190]
Hello, 

I have collected EEG data from 70 channels under 5 experimental conditions. Now using LIMO I would like to perform cluster analysis for any 2 condition to identify the significant electrodes and the significant timestamps where there was an effect or difference between the 2 experimental condition. I am attaching the screenshots of the steps I have followed.                                                                                                  
P.S : I tried 2nd level analysis using repeated ANOVA. I choose "faces" and "repetition" as factors with 2 values. I am not sure about this step. I assumed that it is a step to choose the number of experimental conditions that we would like to choose to perform cluster analysis

Expected Output: 
I would like to see clusters indicating the  start and the end time in ms. Also the maximum F-value observed at which particular timestamp and the significant electrode.

Kindly let me know how can I rectify this issue. 

![image1](https://github.com/LIMO-EEG-Toolbox/limo_tools/assets/97448967/782e85d5-1db8-4c06-93e2-485749e80f9e)
![WhatsApp Image 2024-01-30 at 20 45 48](https://github.com/LIMO-EEG-Toolbox/limo_tools/assets/97448967/f957c7bf-f6c6-430c-a222-f26d1e11fe16)
![WhatsApp Image 2024-01-30 at 20 45 49](https://github.com/LIMO-EEG-Toolbox/limo_tools/assets/97448967/2c118a41-6fb8-4e4c-958f-fec559f54e05)
![WhatsApp Image 2024-01-30 at 20 45 49 (1)](https://github.com/LIMO-EEG-Toolbox/limo_tools/assets/97448967/5a684fd4-a280-4f4c-8cfa-1968f0d41618)
![WhatsApp Image 2024-01-30 at 20 45 49 (2)](https://github.com/LIMO-EEG-Toolbox/limo_tools/assets/97448967/aedac843-42c9-4e9a-b7dc-b9de56751efb)
![WhatsApp Image 2024-01-30 at 20 45 49 (3)](https://github.com/LIMO-EEG-Toolbox/limo_tools/assets/97448967/e9ea2664-354f-4843-98dc-9f3d634d0f86)
![WhatsApp Image 2024-01-30 at 20 45 49 (4)](https://github.com/LIMO-EEG-Toolbox/limo_tools/assets/97448967/2ee88853-876a-4351-824b-4bb0e0be02b3)
![WhatsApp Image 2024-01-30 at 20 45 49 (5)](https://github.com/LIMO-EEG-Toolbox/limo_tools/assets/97448967/5608f7db-dc35-48df-a0d3-3b4a20e6b794)
![WhatsApp Image 2024-01-30 at 20 45 49 (6)](https://github.com/LIMO-EEG-Toolbox/limo_tools/assets/97448967/c3b576ec-a505-4b1b-818e-f46b98bd6730)
![WhatsApp Image 2024-01-30 at 20 45 49 (7)](https://github.com/LIMO-EEG-Toolbox/limo_tools/assets/97448967/690f08dd-4702-4993-9e8e-4f458a2df51e)
![WhatsApp Image 2024-01-30 at 20 45 49 (8)](https://github.com/LIMO-EEG-Toolbox/limo_tools/assets/97448967/54fd8d13-5a43-45c0-a5aa-014b084bf179)
![WhatsApp Image 2024-01-30 at 20 45 56](https://github.com/LIMO-EEG-Toolbox/limo_tools/assets/97448967/2ee01ec0-2334-4db7-8178-8e1815a4a680)
![WhatsApp Image 2024-01-30 at 20 45 56 (1)](https://github.com/LIMO-EEG-Toolbox/limo_tools/assets/97448967/524f4ed0-f422-43a4-9351-25d101d10102)
![WhatsApp Image 2024-01-30 at 20 45 56 (2)](https://github.com/LIMO-EEG-Toolbox/limo_tools/assets/97448967/c7f1cc3d-242b-47d6-a53e-1378b86a10fb)

**Comment by CPernet** [comment]
resolved?
