### ISSUE TITLE
[BUG] - limo v4.0 is not available under the releases page

### ISSUE THREAD

**Issue by robertoostenveld** [LIMO-EEG-Toolbox/limo_tools#206]
When I go to the releases page at https://github.com/LIMO-EEG-Toolbox/limo_tools/releases and click on the "Source Code (zip)" link which points to https://github.com/LIMO-EEG-Toolbox/limo_tools/archive/refs/tags/v4.0.zip, then I get a 404 not found error. 

This appears to be an issue with the release. Perhaps you want to recreate the v4.0 release, or a make a newer (and slightly  updated) release as v4.1.

**Comment by CPernet** [comment]
solved? (downloads for me even when unsigned)
