### ISSUE TITLE
Minor: limo_clustering "text" needs double instead of single

### ISSUE THREAD

**Issue by behinger** [LIMO-EEG-Toolbox/limo_tools#23]
Function: *limo_clustering*
For whatever reason my `maxval` was a "single" which the plotting function did not like.
before:
```
text(loc,maxval,txt,'FontSize',10,'HorizontalAlignment','right');  
```
after
``` 
text(loc,double(maxval),txt,'FontSize',10,'HorizontalAlignment','right');
```

I also think if fig = 0 is specified the figure should not open regardless of whether any significant results were found.

**Comment by CPernet** [comment]
thx for the fix -- for the fig, the gui calls without argument which make the fig empty
if no sig and fig empty do the figure -- if you code it and use fig = 0 it will never plot

no pushed yet, it's in a branch with a few other updates to come soon
thx
