### ISSUE TITLE
Miror: two sample t-test second level

### ISSUE THREAD

**Issue by arnodelorme** [LIMO-EEG-Toolbox/limo_tools#26]
The array of folder seems wrong. I believe the first 2 elements are correct and elements 3 to 24 are garbage that is not needed.

![Screen Shot 2019-08-13 at 7 27 27 PM](https://user-images.githubusercontent.com/1872705/62990554-48f87d00-be01-11e9-9722-b69872a70c32.png)

**Comment by CPernet** [comment]
wow how did you get that? this is generated in limo_random_select when you specify which data to use ie got to be 2*1 cell array ?? cannot reproduce so far
