### ISSUE TITLE
Issues with study structure and cluster correction

### ISSUE THREAD

**Issue by Andesha** [LIMO-EEG-Toolbox/limo_tools#33]
Hi there,

I have a study where I am attempting to do cluster correction on a 2x2 analysis. To achieve this we are attempting to use the EEGLAB study structure.

Here are some images depicting the structure:

![Screenshot from 2019-11-26 15-00-19](https://user-images.githubusercontent.com/10199995/69668977-f1ec8000-105e-11ea-9882-7b8e823e5c4f.png)

![Screenshot from 2019-11-26 15-00-30](https://user-images.githubusercontent.com/10199995/69668983-f44eda00-105e-11ea-93f2-c0fb5be1790f.png)

![Screenshot from 2019-11-26 15-00-49](https://user-images.githubusercontent.com/10199995/69669009-ff096f00-105e-11ea-8e86-a3ea22201b5c.png)

After this, we compute the ERPs via "precompute channel measures" EEGLAB.

Next, we do the following by "Estimate model parameters (channel)":

![Screenshot from 2019-11-26 15-03-18](https://user-images.githubusercontent.com/10199995/69669024-0597e680-105f-11ea-93cb-3a31c89a07c0.png)

After this runs for awhile we get the following error:

![Screenshot from 2019-11-26 15-04-42](https://user-images.githubusercontent.com/10199995/69669033-0a5c9a80-105f-11ea-9f0e-fc9044d52d49.png)

Any ideas? 

Thanks very much! :)

**Comment by CPernet** [comment]
the new study requires you to have a single .set, we it pulls out conditions on the fly we for you select factors in the design - we probably should remove the 'condition' column @arnodelorme from the interface?
