### ISSUE TITLE
Cannot execute second-level analyses via GUI due to MATLAB crashing

### ISSUE THREAD

**Issue by Bysmuth** [LIMO-EEG-Toolbox/limo_tools#34]
I am using LIMO v2.0 and EEGLAB v2019.1 on a laptop running macOS 10.13.4 and MATLAB_R2018b.

When I attempt to use the LIMO GUI to run most second-level analyses, MATLAB crashes. Specifically, after loading the GUI, clicking "Random effects", and loading an expected chan / neighbours file (such as the one provided in the tutorial), clicking almost any of the buttons causes MATLAB to crash on my computer. Here is a list of buttons that, when clicked, lead to crashes:

Basic stats [crash occurs immediately after clicking]:
	Central tendency and CI
	Parameter plots

Tests [crash occurs immediately after I indicate on a subsequent popup window whether I want to perform a "Full scalp analysis" or analyze "1 channel/component only"]:
	One Sample t-test
	Two Samples t-test
	Paired t-test
	Regression

The following buttons do NOT cause MATLAB to crash (or they at least successfully bring up further windows; I didn't actually execute the analyses):

Basic stats:
	Plot central tendency and CI
	Make and plot a difference

Tests:
	ANOVA/ANCOVA

**Comment by Bysmuth** [comment]
It seems like the problem occurs when limo_get_files() is called. For comparison, when I replaced that function with the version from LIMO v1.5 (while keeping all other files from LIMO v2.0), it brought up the file selection window as expected.

(Note to anyone else stumbling across this prior to a fix being issued: This workaround also caused limo_random_select() to raise an error because it didn't know what to do with my .txt file, as the functionality of identifying .mat files from a .txt file seems to have been added between versions. Accordingly, I made a hybrid version of limo_get_files() that is the same as v1.5's except that I replaced lines 19-37 with lines 62-88 from v2.0's. I don't expect this to work for all situations!)

**Comment by JohnAtl** [comment]
In `limo_get_files.m` comment out lines 37-41 to fix the crashing problem.
```
% if ~ispc
%     filter(:,2) = {';'};
%     filter = filter';
%     filter = strcat(filter(:));
% end
```

**Comment by CPernet** [comment]
yes we have issues depending on OS, can you specify Win/MAC/Linux? thx

**Comment by Bysmuth** [comment]
I use OS X (10.13.6).

**Comment by CPernet** [comment]
changed now with {} also fixes the issue
