### ISSUE TITLE
Regression analyses ignore parameter selection

### ISSUE THREAD

**Issue by Bysmuth** [LIMO-EEG-Toolbox/limo_tools#35]
In limo_random_select.m of LIMO v2.0, the loop through regression parameters is accomplished by the following code (line 453):

`for i=length(parameters)`

rather than 

`for i=parameters`

This causes LIMO always to select regressor n, where n is the number of parameters provided. This behavior seems likely to lead users to perform and interpret analyses incorrectly without knowing it.

Although I have not tried running v1.5, this issue appears not to be present in that version (line 287 loops through parameters correctly).

I also encountered a couple of other potential issues with limo_random_select.m that arise only when it is called from a script:

1) When getting files, several lines reference g.limofiles{1} when g.limofiles was probably intended (potentially lines 132, 135 and 136), leading to errors.

2) The check for FilterIndex on line 396 fails (i.e., it is undefined) if 'regfile' is passed as a parameter.

**Comment by CPernet** [comment]
I'll check all those for the forthcoming version - thx
