### ISSUE TITLE
calculating expected chanlocs

### ISSUE THREAD

**Issue by anomalosepia** [LIMO-EEG-Toolbox/limo_tools#36]
When I'm calculating expected chanlocs, I get an error during the plotting. 
it looks like there was a hard coded '71' on line 117 of limo tools

```
topoplot(zeros(1,71), expected_chanlocs,'style','blank','electrodes','labelpoint','chaninfo',expected_chanlocs);

```
I changed this to 
`topoplot(zeros(1, length(expected_chanlocs)), expected_chanlocs,'style','blank','electrodes','labelpoint','chaninfo',expected_chanlocs);
`
seems to fix the issue.

**Comment by CPernet** [comment]
hey thx for catching this -- I've set it in the forthcoming version (WS branch)
