### ISSUE TITLE
Inconsistency between constant color for plotting design

### ISSUE THREAD

**Issue by arnodelorme** [LIMO-EEG-Toolbox/limo_tools#38]
When using the function

limo_random_robust

from the command line and choosing not to use z-score, the design is being shown and it has the constant white. However, when reviewing the design in the LIMO plot GUI, the constant is in black. This does not happen if one chooses to z-score regressors (constant is white in both cases). See screen captures.

**Comment by arnodelorme** [comment]
<img width="485" alt="Screen Shot 2020-04-23 at 11 44 34 AM" src="https://user-images.githubusercontent.com/1872705/80126291-7bde3d80-8558-11ea-9f96-e6b497864c88.png">

**Comment by arnodelorme** [comment]
<img width="510" alt="Screen Shot 2020-04-23 at 11 46 59 AM" src="https://user-images.githubusercontent.com/1872705/80126300-81d41e80-8558-11ea-9f47-f8c0edb990d8.png">

**Comment by CPernet** [comment]
fixed
