### ISSUE TITLE
error loading .study file in "create single trials"

### ISSUE THREAD

**Issue by sarhen907** [LIMO-EEG-Toolbox/limo_tools#42]
I have been following the tutorial in an attempt to load in my .study file and I keep getting the following error. Any assistance is appreciated!

Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)limo_create_single_trials_gui('load_data_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.

**Comment by CPernet** [comment]
at which stage does this happen? (do try the WLS branch, it will be merged to master soon)
