### ISSUE TITLE
Error in function checkoldformat at line 264

### ISSUE THREAD

**Issue by amisepa** [LIMO-EEG-Toolbox/limo_tools#44]
Hi,

Another error I have been encountering recently. It only occurs when I use aggressive cleaning thresholds on my data. 

![image](https://user-images.githubusercontent.com/58382227/89480671-ef9d0280-d763-11ea-87a1-dcd16570b159.png)
![image](https://user-images.githubusercontent.com/58382227/89480864-77830c80-d764-11ea-827b-7435f36ba5bc.png)

It is not due to missing/interpolated electrodes. 
Is there a minimum file length or maximum nmber of boundaries? This on small continuous files. 
mean length of files with error = 32.4 s
mean length of files without error = 90 s

min length of files with error = 24 s
min length of files without error = 32.4 s

max length of files with error = 47 s
max length of files without error = 316 s

**Comment by CPernet** [comment]
yes, because the weighted least squares optimization fails as you do not have enough remaining trials 
WLS will take care of noisy trials so you can relax cleaning criteria (same for me used ASR too aggressively)
