### ISSUE TITLE
Error in std_limo() at line 548

### ISSUE THREAD

**Issue by amisepa** [LIMO-EEG-Toolbox/limo_tools#45]
Hi Cyril,

I get this error now after the recent merge and pull during 1st level.
The 'factors' structure doesn't seem to have a 'value' field.  
![image](https://user-images.githubusercontent.com/58382227/93963752-df8cb280-fd12-11ea-83a6-5911b83f9f11.png)

As before, I just have one variable with a well-being score (1-100), to correlate to EEG.

Thanks,
Cedric

**Comment by CPernet** [comment]
std issue not limo -- new release fixed

**Comment by amisepa** [comment]
Hi Cyril,

I got the most recent LIMO re-installed and I am still encountering this issue. 

I have factors =  struct with fields:
    vartype: 'continuous'
      label: 'aios'
      level: 'one'

But no value field

**Comment by CPernet** [comment]
Maybe Arno can help ... Coding isdue? No time sorry


--
Dr Cyril Pernet,
Senior Academic Fellow
Neuroimaging Sciences

Centre for Clinical Brain Sciences
Chancellor's Building, Room GU426D
The University of Edinburgh
49 Little France Crescent
Edinburgh BioQuarter EH16 4SB

cyril.pernet@ed.ac.uk
tel:  +44 (0)131 465 9530
http://www.sbirc.ed.ac.uk/cyril
http://www.ed.ac.uk/edinburgh-imaging
<http://www.ed.ac.uk/edinburgh-imaging>

________________________________

**Comment by arnodelorme** [comment]
We have disabled contrast for continuous variables. Working now.
