### ISSUE TITLE
2nd level passing all files

### ISSUE THREAD

**Issue by CPernet** [LIMO-EEG-Toolbox/limo_tools#48]
turns out https://github.com/LIMO-EEG-Toolbox/limo_tools/blob/HotFixes/limo_random_select.m doesn't deal well with passing all files as inputs -- no files or txt files fine, but bugs for cell array of names  - calling breaklimofiles usually on a single file (dimension handling issue)

within eeglab study all good - but need fixing for command line

**Comment by LucaLaFisca** [comment]
The issue was due to an infinite loop in limo_get_files function. It has been fixed now.

**Comment by CPernet** [comment]
which commit? you cannot change limo_get_files

**Comment by CPernet** [comment]
now fixed by https://github.com/LIMO-EEG-Toolbox/limo_tools/commit/0e42d54d01b105f7bc645a8c55d5bee4724d1c0e
