### ISSUE TITLE
Issue with EEGLAB/BIDS sessions

### ISSUE THREAD

**Issue by arnodelorme** [LIMO-EEG-Toolbox/limo_tools#53]
From the EEGLABLIST:

My original study design has intra individual factor of pre/post
intervention and interindividual factor of active or sham group.

To start LIMO processes, I created a new design that is just the
intraindividual factor of session.

The issue is that the study files are saved by ID and session, so person 12
is 12_ses-1.dattimef and 12_ses-2.dattimef. LIMO is trying to find a file
of 12.dattimef, instead. So I get an error that it cannot find 12.dattimef.

I tried to re-precompute variables based just on group design and just
based on session design, but both were unsuccessful.

**Comment by CPernet** [comment]
it's in std_limo that we need to make changes -- but we also need to decide how we want to handle designs by default
