### ISSUE TITLE
limo_random_select: Matrix dimensions must agree error in single-channel second level analysis.

### ISSUE THREAD

**Issue by Elisabeth-Pares** [LIMO-EEG-Toolbox/limo_tools#55]
Hi, 

I think I found a small bug in the implementation of single-channel second level analysis. 
The code initially crashed with the following error message:

Matrix dimensions must agree.

Error in limo_random_select (line 1211)
                            all(size(squeeze(matched_data)) ==
                            size(squeeze(data(:,:,:,:,1))))

I think this is because the indexing in data has one too many dimensions - it should be 4 instead of 5 in simple ERP analysis. Removing one of the ':' dimensions fixed the issue and produced the expected results for me.

I hope this helps! 

Elisabeth

**Comment by CPernet** [comment]
yep that is it - thank you very much for reporting that bug ! not many people use the optimized single channel approach, do let me know how it goes for you - happy to debug if needed (likely same dimension issues)
fix in the next released https://github.com/LIMO-EEG-Toolbox/limo_tools/commit/87d1ebc28e1683ebb281d9d40d7d97bad4766270
