### ISSUE TITLE
limo_cluster_test not found 

### ISSUE THREAD

**Issue by amisepa** [LIMO-EEG-Toolbox/limo_tools#65]
I processed all my results for main effect and each contrast with both cluster and TFCE correction and was able to look at the corrected results, but then after I closed Matlab and wanted to look at the results again after loading the study into EEGLAB, I receive this error for the cluster correction. I checked and the H0 repo seems to contain its files, and TFCE still works. So something specific to Cluster-correction stops working after closing LIMO/EEGLAB/Matlab. 
A temporary file necessary to view the results maybe? 
The only way for me to look at them again currently is to recompute the results, which takes a while. 

![image](https://user-images.githubusercontent.com/58382227/109567904-f8a44700-7a9a-11eb-8d19-138c15242421.png)

Thanks in advance,
Cedric

**Comment by CPernet** [comment]
now that you added the subdirectory - prblem solved

**Comment by amisepa** [comment]
Yes that worked, sorry I forgot to close it. Unclear why the path was removed though, but probably something I did.
