### ISSUE TITLE
HDI: Central tendency and CI from Betas parameters 1:2

### ISSUE THREAD

**Issue by amisepa** [LIMO-EEG-Toolbox/limo_tools#67]
Steps:
1) Central tendency > Betas > Mean > select 'Beta_files_Gp1_valence_GLM_Channels_Time_IRLS.txt' > parameters [1 2] > Full brain analysis 

gathering data ...
processing subject 38

--> error

Unable to perform assignment because the indices on the left side are not compatible with the size of the right side.
Error in limo_central_tendency_and_ci (line 414)
                    data(:,:,i)     =
                    limo_match_elec(subj_chanlocs(i).chanlocs,expected_chanlocs,begins_at,ends_at,squeeze(Yr(:,:,parameters)));
Error in limo_random_effect>Central_tendency_and_CI_Callback (line 89)
    limo_central_tendency_and_ci(handles.chan_file);
Error in gui_mainfcn (line 95)
        feval(varargin{:});
Error in limo_random_effect (line 29)
    gui_mainfcn(gui_State, varargin{:});
Error in
matlab.graphics.internal.figfile.FigFile/read>@(hObject,eventdata)limo_random_effect('Central_tendency_and_CI_Callback',hObject,eventdata,guidata(hObject)) 
Error while evaluating UIControl Callback.

**Comment by CPernet** [comment]
i cannot reproduce the error - i would need access to the data 
note i made recent changes that might fix that? see hotfixes branch

**Comment by amisepa** [comment]
Sorry, just tried again after doing a pull from HotFixes and still have the problem. 

error is now line 450:                     
`data(:,:,i)     = limo_match_elec(subj_chanlocs(i).chanlocs,expected_chanlocs,begins_at,ends_at,squeeze(Yr(:,:,parameters)));`

-> "Unable to perform assignment because the indices on the left side are not compatible with the size of the right side. "

Only thing I see on that line is expected_chanlocs doesn't have reference fields as opposed to subj_chanlocs(i).chanlocs. But I added it manually and it still dosn't work, so must be something else. 
begins_at = 1
ends_at = 376
size of squeeze(Yr(:,:,parameters)) =   64   376     2

**Comment by CPernet** [comment]
see above - doesn't bug so something in your data

**Comment by amisepa** [comment]
Ok I'll look into it thanks
