### ISSUE TITLE
2% trimmed means?

### ISSUE THREAD

**Issue by JohnAtl** [LIMO-EEG-Toolbox/limo_tools#68]
Hello,
It seems in limo_robust_rep_anova, the argument '2' to limo_trimmed_mean() would yield 2% trimmed means, rather than the customary 20%. Is this correct?
Thanks

https://github.com/LIMO-EEG-Toolbox/limo_tools/blob/bba57e3ac74380720188d8fc0f3df1a6f18f578f/limo_robust_rep_anova.m#L124

**Comment by CPernet** [comment]
oops yes, indeed thx for spotting it 
please be very careful with this function, it's not validated yet (you can see it not called by any other functions, not is in the wiki) -- one factor works that's pretty much it

**Comment by CPernet** [comment]
pushed the changes in both master and hotfixesm, thx

**Comment by JohnAtl** [comment]
Hi Cyril,

limo_trimmed_mean is called from limo_robust_rep_anova, which is what I was really interested in. (Although I can't figure out the structure for Data, since it is time x subject x measures, but represents more than one condition. Any suggestions?)

Has limo_rep_anova not been validated?

Do you have suggestions for robust anova and post-hoc tests on related/dependent data? (It doesn't fit in study since each sample is taken at a different time point, depending on subjects' movement.)

Struggling grad student with non-normal EEG data would be most grateful for suggestions.

Thanks,
John
