### ISSUE TITLE
EEGlab LIMO data analysis issue

### ISSUE THREAD

**Issue by arnodelorme** [LIMO-EEG-Toolbox/limo_tools#71]
Transferred from https://github.com/sccn/eeglab/issues/350

Hi,

Do you provide assistance with data analysis using the LIMO plugin? I have run the data set twice and both times the beta files are empty, although the program is generating the output files for each subject. The other steps to the analysis worked fine and I can compute channel and component measures when using just EEGlab without LIMO.

Thanks,
Jay

**Comment by arnodelorme** [comment]
@sasis001 I have transferred your issue. Would you mind providing access to the data?

**Comment by sasis001** [comment]
I have shared a google drive folder consisting of the files. 

Thanks,
Jay

**Comment by arnodelorme** [comment]
Thanks. We will look at it.

**Comment by CPernet** [comment]
step 1 - run OLS (although WLS should have leave you a message)

**Comment by sasis001** [comment]
I ran the data with the OLS option and the analysis went through for the channel measures. 
However, when I tried the same thing with the component analysis it did not go through for any of the measures (ERP, Spectrum, ERSP). I could view the components on EEGlab with preclustering. Hence, the components are all generated for the different measures. 

Excerpt from the error message generated-
Error using load
Unable to read file 'Yr'. No such file or directory.
File C:\matlab\eeglab_current\eeglab2021.0\plugins\LIMO3.0\limo_glm_handling.m at line 18
File C:\matlab\eeglab_current\eeglab2021.0\plugins\LIMO3.0\limo_eeg.m at line 473
File C:\matlab\eeglab_current\eeglab2021.0\plugins\LIMO3.0\external\psom\psom_run_job.m at line 214
File C:\matlab\eeglab_current\eeglab2021.0\plugins\LIMO3.0\external\psom\psom_run_job.m at line 128
File C:\matlab\eeglab_current\eeglab2021.0\plugins\LIMO3.0\external\psom\psom_run_script.m at line 437
File C:\matlab\eeglab_current\eeglab2021.0\plugins\LIMO3.0\external\psom\psom_run_script.m at line 323
File C:\matlab\eeglab_current\eeglab2021.0\plugins\LIMO3.0\external\psom\psom_pipeline_process.m at line 591
File C:\matlab\eeglab_current\eeglab2021.0\plugins\LIMO3.0\external\psom\psom_run_pipeline.m at line 417
File C:\Program Files\MATLAB\R2021a\toolbox\matlab\lang\parallel_function.m at line 832
File C:\Program Files\MATLAB\R2021a\toolbox\parallel\remoteParallelFunction.m at line 67

****************
Checking outputs
****************
The output file or directory C:\matlab\eeglab_current\eeglab2021.0\subj files\set\data files\sub-8\design1_GLM_Components_Time_OLS\Betas.mat has not been generated!

 

Thanks,
Jay

**Comment by CPernet** [comment]
if you look into the psom report of subjects, it looks like to me it cannot generate the design and associate the IC data (Yr) and thus lino_glm cannot load something that doesn't exist -- see https://github.com/LIMO-EEG-Toolbox/limo_tools/wiki/debugging-1st-level-stats to get the actual error

thx

**Comment by CPernet** [comment]
PS: when running WLS didn't you get an error or warning message? like those here https://github.com/LIMO-EEG-Toolbox/limo_tools/blob/master/limo_batch.m#L536

**Comment by arnodelorme** [comment]
Is there something for me to do/test?

**Comment by CPernet** [comment]
let's see what the error is - I cannot see why it can process channels but not IC, maybe a bug related to clustering (as one reorganize the IC data so each subject has the same IC*frame matrix) ; unless of course you have time to play with that

**Comment by arnodelorme** [comment]
No time. Will help if my expertise is needed though or if there is a problem with EEGLAB/LIMO integration

**Comment by arnodelorme** [comment]
Message from Jay

I appreciate your help with this. I have uploaded the files from the EEGlab component analysis and the errors from the LIMO component analysis (also see attached) to the shared google drive folder. I have also uploaded the files from the channel WLS analysis. I followed the instructions provided in the EEGlab workshops and 11 components were identified across all subjects via the initial EEGlab analysis. 

https://drive.google.com/drive/folders/1opwBe6zwenfDK5tww9PfSFh7hUGJkwXq

Also, the channel level analysis only worked with OLS and not WLS. Is this ok and if not, why is the analysis not working for WLS?

Thanks,
Jay

**Comment by CPernet** [comment]
For both channels and component, only your subject 1 is processed because in all other cases there is an issue with the number of trials extracted vs. the number of conditions defined -- that is your conditions do not match trials

**Comment by sasis001** [comment]
A few sets had to be excluded due to noisy data or other issues. This is the reason for unequal trials across the four conditions in the study. Is there an option to find out how many trials in each condition in the entire data set and a workaround to fixing the issue?

Thanks,
Jay

**Comment by CPernet** [comment]
Unequal number of trials is not an issue, the problem is triggers and
segments don't match, it's a preprocessing problem - not a LIMO issue.

**Comment by sasis001** [comment]
>>the problem is triggers and segments don't match.
This error is surprising. Can you say which step in preprocessing or how this can be fixed? 


and/or should I do epoching at the subject instead of the study level?

**Comment by CPernet** [comment]
sorry, check with EEGLAB email-list, help, I do not know how this kind of problem occurs. As you can see from the LIMO tutorial (https://github.com/LIMO-EEG-Toolbox/limo_meeg/wiki/1.-Preprocessing) I epoch on the whole dataset and this usually work
