### ISSUE TITLE
warndlg2() instead of warndlg() called in limo_batch_gui line 481

### ISSUE THREAD

**Issue by NirOfir** [LIMO-EEG-Toolbox/limo_tools#73]
Not sure if it is intended or not. Is LIMO supposed to be able to run on a machine without EEGLAB? If so, I guess this call should be changed to warndlg() instead. Should I make a PR?

**Comment by CPernet** [comment]
I tried to curate the code, usually 
if ~exist('warndlg2',file)
    warndlg('...')
else
   warndlg2('...')
end

thanks for going through stuff --> https://github.com/LIMO-EEG-Toolbox/limo_tools/blob/master/contributors.md

**Comment by NirOfir** [comment]
Cool, will do. I see now that line 472 calls to warndlg() instead. Should I change both to this if solution (call warndlg2 if possible)?

**Comment by CPernet** [comment]
yes I use that bit of code above in many places but haven't been very systematic ...

**Comment by NirOfir** [comment]
Thanks! I made the PR now.
