### ISSUE TITLE
File structure

### ISSUE THREAD

**Issue by SVH35** [LIMO-EEG-Toolbox/limo_tools#76]
Hi everyone

I have a problem with running the first level analyses. I have a study consisting of 4 participants, two older adults (O11 and O13) and two younger adults (Y106 and Y107) (see figure). In each folder (e.g., sub-O11), there are 6 .set files, containing preprocessed data of 6 different conditions. In addition, a .dattimef is in each folder (i.e., the precomputed time-frequency data). All this info is contained in a study structure (subject, condition and group are used).

I have structured the data identical to the the data structure of the tutorial dataset (each subject in a folder, all conditions of that subject in the aforementioned folder). However, in the derivates folder, only one folder is created: the folder of the first subject. This folder seems to be used by every analysis following the first one, and the matlab files created (betas.mat, yr.mat,...) are just replaced. The pipeline itself runs perfectly. 

![image](https://user-images.githubusercontent.com/88398607/128065368-01ddf414-892c-42fd-a8f4-e8e9fb4974f3.png)

Does anyone know what might be causing this bug? Your help would be greatly appreciated

Sincerely

**Comment by ChristineLackner** [comment]
I had a similar problem. You need one .set file for each participant with all of the conditions merged together.

**Comment by CPernet** [comment]
thx @ChristineLackner this is indeed the solution
