### ISSUE TITLE
p-values assigned as stat_values in limo_display_results() when using cache

### ISSUE THREAD

**Issue by NirOfir** [LIMO-EEG-Toolbox/limo_tools#84]
When limo_display_results() uses cached data from the LIMO structure, the p values are assigned as stat_values to the base workspace (https://github.com/LIMO-EEG-Toolbox/limo_tools/blob/567d6da5d409fd5a8aac354669c1b4b369e50430/limo_display_results.m#L1071). Based on the rest of the code - particularly line 1136 when the cache isn't used, I think line 1071 should be changed into:
`assignin('base','stat_values',toplot)`

Is that correct? I can make a PR to hot fixes.

**Comment by CPernet** [comment]
ideally, we should always have the F and p values and for 'maps' the clusters ; maybe using 'stat_values' as variable name isn't explicit enough

**Comment by NirOfir** [comment]
I think we do have all of them, it's just this one line of code that overwrote one of them (M is the p values map).

**Comment by CPernet** [comment]
ah ok then
