### ISSUE TITLE
Correct percent limit for trimmed mean

### ISSUE THREAD

**Issue by NirOfir** [LIMO-EEG-Toolbox/limo_tools#89]
limo_trimci() checks that the percent trimming is between 0 and 100. Since the same percent is trimmed from both sides of the distribution, if someone sets percent > 50, that means that more than 100% of the data should be removed... I suggest to limit percent in the range 0-50 (or maybe smaller, if the median is also not supported). What do you think?

**Comment by CPernet** [comment]
makes sense! maybe up to 30% and if more - warning message + return?

**Comment by NirOfir** [comment]
Sounds good. I think warning + return is like error(), right?

**Comment by CPernet** [comment]
i would instead set to the max say 30%, warning('maximum trimming set to 30%'); and not breaking code

**Comment by NirOfir** [comment]
Ah, got you, that makes sense.
