### ISSUE TITLE
No control over trimmed mean behavior through limo_random_select()

### ISSUE THREAD

**Issue by NirOfir** [LIMO-EEG-Toolbox/limo_tools#90]
I tried replicating an analysis using normal rather then trimmed means (or just changing the trimming percentage), and noticed that when calling limo_random_select(), method is always set to 'Trimmed mean', although it seems like limo_random_robust() and limo_trimci do allow controlling whether (and to what extent) the means should be trimmed. I'm not entirely sure how to give users control over it through limo_random_select(). Maybe adding these as optional inputs?

**Comment by CPernet** [comment]
yes, ideally the LIMO field will tell if means or trimmed means and the corresponding stat is used - with in most cases the easiest option setting 0% trimming and still calling the same limo functions :-) although we do have some basic t-tests as well 

note this should be for people calling the function by hand, and leave trimming as default (as discussed in another issue I do not intend to have non robust approaches fully supported)

**Comment by NirOfir** [comment]
I agree completely :) I'm not sure right now that the code is modular enough to be easily called "by hand", but I hope it's possible to get there.
