### ISSUE TITLE
cfg channel structure and std_gettrialsind

### ISSUE THREAD

**Issue by amisepa** [LIMO-EEG-Toolbox/limo_tools#92]
Hi,

I get 2 errors during 1st level LIMO (HotFixes branch with the latest pull). The first one doesn't interrupt the process, the second one does. This is on ERP data with 3 conditions. Data are imported with pop_importbids.

**1. First one:** 
![error_limo_1st-lvl](https://user-images.githubusercontent.com/58382227/142482747-7eea6b66-cebf-4560-bdbf-a2bf9b049de9.png)
I used the 10-20 BEM chanlocs during preprocessing, and saved the file a .ced for BIDS import. 

**2. Second one:**

```
Error using std_gettrialsind (line 136)
Type error - excepting numerical values for field type
Error in std_limodesign (line 125)
                trialindsx = std_gettrialsind(trialinfo, limodesign.categorical{iVar}{iVal}{:});
Error in std_limo (line 418)
            [catMat,contMat,limodesign] = std_limodesign(factors, trialinfo, 'splitreg', 'off', 'interaction', opt.interaction);
Error in pop_limo (line 168)
[STUDY,limofiles] = std_limo(STUDY, ALLEEG, options{:});
Error in eeg_processings (line 310)
pop_limo(STUDY, ALLEEG, 'method','OLS','measure','daterp','timelim',[-100
950],'erase','on','splitreg','off','interaction','off');
```

Thanks in advance

**Comment by CPernet** [comment]
issue from EEGLAB new structure, @Arno fixed it
