### ISSUE TITLE
How should I enter "Which parameters to test?"

### ISSUE THREAD

**Issue by vatthaphon** [LIMO-EEG-Toolbox/limo_tools#93]
Dear All, 

This might be not an issue but I don't know where to ask a question about using LIMO. I then apologize if I post the topic in the wrong place.

I am learning to use LIMO 3.2 on EEGLab v2021.0 by examining the example given by https://github.com/LIMO-EEG-Toolbox/limo_meeg/blob/master/resources/from_bids2stats.m. I set a breakpoint at line 1238 of limo_random_select.m, which is called from the line 91 of from_bids2stats.m, to print out “parameters(i,:)”.  Matlab reports that “parameters(i,:)” equals [1, 2, 3, …, 9]. I tried to achieve the same thing using GUI. What I did is that I pause executing limo_random_select, and click Study->LIMO (Beta)->2nd level analysis. After selecting “Load expected chan” and “Working directory”, I click the ANOVA/ANCOVA button. I select “Repeated Measures ANOVA”, “Full scalp analysis”, enter 1 for “How many independent groups?”, enter [3 3] for “Enter repeated factors level?”, select the beta file, and enter {[1 2 3], [4 5 6], [7 8 9]} in “which parameters to test?”. I print out “parameters(i,:)” that is now a cell of {[1 2 3], [4 5 6], [7 8 9]}. The value of “parameters(i,:)” from my input is different from the script from_bids2stats.m. It would be very kind of you if someone could please help me to guide what I did incorrectly.

Sorry for the long explanation.

Best,
Atthaphon Viriyopase

**Comment by CPernet** [comment]
for a GUI version please see https://github.com/LIMO-EEG-Toolbox/limo_meeg/wiki/7.-Two-ways-ANOVA-(Faces-x-Repetition) 1 group 2 factors [3 3] parameters [1:9]
