### ISSUE TITLE
Possible typo error in limo_display_results?

### ISSUE THREAD

**Issue by vatthaphon** [LIMO-EEG-Toolbox/limo_tools#96]
Hi All,

I have LIMO 3.2. At line 1502 of limo_display_results.m, it states "elseif contains(['Modelled','Modeled'],extra,'Ignorecase',true)". Should not it be  "elseif contains(extra,['Modelled','Modeled'],'Ignorecase',true)" instead?

Best,
vattha

**Comment by CPernet** [comment]
hey thx for that, indeed that's the way using a cell array  contains(extra,{'Modelled','Modeled'},'Ignorecase',true) -- just pushed the fix on master
